class AppError(Exception): ...
class ValidationError(AppError): ...
class AuthError(AppError): ...
class NotFoundError(AppError): ...
class PermissionError(AppError): ...
class InsufficientStockError(AppError): ...